\documentclass[11pt,a4paper]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}
\usepackage{booktabs}
\usepackage{siunitx}
\usepackage{graphicx}
\usepackage[margin=2.4cm]{geometry}
\usepackage{hyperref}
\usepackage{caption}
\usepackage{subcaption}
\sisetup{group-separator={\,},group-minimum-digits=4}
\captionsetup{font=small}
\captionsetup[table]{position=below}
\title{Measured Inference Cost of Coupled Models}
\author{Automated report generated by \texttt{analyze.py}}
\date{{{date}}}

\begin{document}
\maketitle

\begin{abstract}
This report quantifies the measured inference cost of {{model_count}} TorchScript models along four axes: executed arithmetic (hardware instruction counters), on-device HBM3 and L2 traffic, host$\leftrightarrow$device PCIe payload, and latency/throughput. All values are hardware-counter or activity-trace measurements and are reproducible from the raw run data.
\end{abstract}

\section{Objective and Measurement Setup}
{{overview_text}}

{{ladder_list}}

{{group_text}}

{{model_table}}

\section{Measurement Methodology}
{{methodology_arithmetic}}

\subsection{Memory traffic}
{{methodology_memory}}

\subsection{Host--device transfer}
{{methodology_transfer}}

\subsection{Adaptive batch discovery}
{{methodology_ladders}}

\section{Results}
{{results_text}}

{{measured_b1_table}}

{{measured_b_table}}

\section{Figures}
{{figures_text}}

\section{Limitations and Conventions}
{{limitations_text}}

\end{document}
