[provider]
class = "AIX"
model_file = "/hpcwork/ro092286/smartsim/mini_app/train_models/model_a/best_model_jit_perfect_model_flat.pt"

[normalization]
class = "MinMax"
input_min = 0.0
input_max = 1.0
output_min = 0.0
output_max = 1.0

[behavior]
class = "Default"

[application]
class = "ModuleTestApplication"
